version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./files:/app/files
    environment:
      - PYTHONUNBUFFERED=1
    ports:
      - 1701:5000
    networks:
      - bot-network

volumes:
  bot-cache:

networks:
  bot-network:
    driver: bridge
