version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./files:/app/files
    environment:
      - PYTHONUNBUFFERED=1
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - TENOR_API_KEY=${TENOR_API_KEY}
    networks:
      - bot-network
    restart: always
  logserver:
    build:
      context: .
      dockerfile: ./log-server/Logserver-Dockerfile
    ports:
      - 1701:1701
    volumes:
      - ./files:/app/files
    restart: always
volumes:
  bot-cache:

networks:
  bot-network:
    driver: bridge
