version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./files:/app/files
    environment:
      - PYTHONUNBUFFERED=1
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - TENOR_API_KEY=${TENOR_API_KEY}
    ports:
      - 1701:5000
      - 28973:28973
    networks:
      - bot-network
volumes:
  bot-cache:

networks:
  bot-network:
    driver: bridge
