version: '3'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - bot-network

volumes:
  bot-cache:

networks:
  bot-network:
    driver: bridge
